# Hyprland Configuration
# https://wiki.hypr.land/Configuring/

# ==================
# ENV
# ==================
source=hyprland/env.conf

# ==================
# MONITOR CONFIG
# ==================
# Monitors from existing configuration
# monitor = eDP-2, 2560x1600@239.998993, 2560x0, 1, vrr, 1
monitor = , preferred,auto,1

# ==================
# EXECS
# ==================
source=hyprland/execs.conf


# ==================
# GENERAL
# ==================
source=hyprland/general.conf

# ==================
# WINDOW RULES
# ==================
source=hyprland/rules.conf

# ==================
# KEYBINDINGS
# ==================
source=hyprland/keybinds.conf




